"""Add groups_support table

Revision ID: 9de2596446f0
Revises: 96b0868d9408
Create Date: 2025-12-15 17:19:27.377411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de2596446f0'
down_revision: Union[str, None] = '96b0868d9408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Проверяем существование таблицы groups_support
    conn = op.get_bind()

    # Вместо op.create_table делаем проверку
    result = conn.execute(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'groups_support')"
    ).scalar()

    if not result:
        op.create_table('groups_support',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('support_id', sa.BigInteger(), nullable=False),
                        sa.Column('group_id', sa.BigInteger(), nullable=False),
                        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                        sa.ForeignKeyConstraint(['support_id'], ['users.id'], ),
                        sa.PrimaryKeyConstraint('id')
                        )
    else:
        # Если таблица уже существует, просто логируем
        print("Таблица 'groups_support' уже существует, пропускаем создание")

    # Остальные таблицы создаём как обычно (если их нет)
    op.create_table('form_tickets_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('message_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('support_id', sa.Integer(), nullable=False),
                    sa.Column('name_cheat', sa.String(length=100), nullable=False),
                    sa.Column('name_game', sa.String(length=100), nullable=False),
                    sa.Column('specifications', sa.String(length=500), nullable=False),
                    sa.Column('problem_description', sa.String(length=1000), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.ForeignKeyConstraint(['support_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('tickets_support_groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('support_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('thread_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups_support.id'], ),
                    sa.ForeignKeyConstraint(['support_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Остальные ALTER COLUMN оставляем как есть
    op.alter_column('banned_users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('medias', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('services', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('medias', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('banned_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('tickets_support_groups')
    op.drop_table('form_tickets_users')
    op.drop_table('groups_support')
    # ### end Alembic commands ###
