"""Добавлен столбец stars в таблицу Orders

Revision ID: 5f63ce4d34a1
Revises: 25060075d232
Create Date: 2025-03-20 14:05:06.056507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f63ce4d34a1'
down_revision: Union[str, None] = '25060075d232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stars', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stars')
    # ### end Alembic commands ###
