"""автовыплаты

Revision ID: 96b0868d9408
Revises: 586a762a49a1
Create Date: 2025-07-31 02:15:12.371688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b0868d9408'
down_revision: Union[str, None] = '586a762a49a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_id', sa.BigInteger(), nullable=False),
    sa.Column('technical_support', sa.Integer(), nullable=False),
    sa.Column('payment_support', sa.Integer(), nullable=False),
    sa.Column('hwid_reset', sa.Integer(), nullable=False),
    sa.Column('get_key', sa.Integer(), nullable=False),
    sa.Column('reselling', sa.Integer(), nullable=False),
    sa.Column('bonus_per_50', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['support_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('support_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_rates')
    # ### end Alembic commands ###
