"""удалил некотрые пунткы в моделе формы

Revision ID: ef8327fa842e
Revises: 92828a77f6e0
Create Date: 2025-12-16 19:40:15.520690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8327fa842e'
down_revision: Union[str, None] = '92828a77f6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('form_tickets_users_user_id_fkey'), 'form_tickets_users', type_='foreignkey')
    op.drop_constraint(op.f('form_tickets_users_support_id_fkey'), 'form_tickets_users', type_='foreignkey')
    op.drop_column('form_tickets_users', 'user_id')
    op.drop_column('form_tickets_users', 'message_id')
    op.drop_column('form_tickets_users', 'support_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_tickets_users', sa.Column('support_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('form_tickets_users', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('form_tickets_users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('form_tickets_users_support_id_fkey'), 'form_tickets_users', 'users', ['support_id'], ['id'])
    op.create_foreign_key(op.f('form_tickets_users_user_id_fkey'), 'form_tickets_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
