"""добавил CASCADE

Revision ID: c09bf27c911b
Revises: ef8327fa842e
Create Date: 2025-12-17 17:13:09.970242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09bf27c911b'
down_revision: Union[str, None] = 'ef8327fa842e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tickets_support_groups_group_id_fkey'), 'tickets_support_groups', type_='foreignkey')
    op.create_foreign_key(None, 'tickets_support_groups', 'groups_support', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets_support_groups', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_support_groups_group_id_fkey'), 'tickets_support_groups', 'groups_support', ['group_id'], ['id'])
    # ### end Alembic commands ###
