"""Изменяем столбец stars

Revision ID: 586a762a49a1
Revises: 5f63ce4d34a1
Create Date: 2025-03-21 22:14:09.551844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586a762a49a1'
down_revision: Union[str, None] = '5f63ce4d34a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
