"""add  MessageSendModel

Revision ID: 686109e2eb5c
Revises: c09bf27c911b
Create Date: 2025-12-25 12:41:35.552845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686109e2eb5c'
down_revision: Union[str, None] = 'c09bf27c911b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
