"""Add order_id in tickets_support_groups

Revision ID: 92828a77f6e0
Revises: 9de2596446f0
Create Date: 2025-12-16 18:56:36.945785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92828a77f6e0'
down_revision: Union[str, None] = '9de2596446f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets_support_groups', sa.Column('order_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'tickets_support_groups', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets_support_groups', type_='foreignkey')
    op.drop_column('tickets_support_groups', 'order_id')
    # ### end Alembic commands ###
